### ISSUE TITLE
bash: schematool: command not found

### ISSUE THREAD

**Issue by marcuswang6** [ntbs1798/big-data-tools-docker-composed#1]
Hi! I am glad to see this repo. Other dockers about big-data-tools are too complicated for me to understand, but yours are excellent. However, I came with this issue during my running `schematool -initSchema -dbType derby`.

I have already config the HIVE_HOME path in .bashrc, wondering how to solve this problem. Thank you!

**Comment by marcuswang6** [comment]
solved by adding `export PATH=$PATH:$HIVE_HOME/bin` to .bashrc

**Comment by ntbs1798** [comment]
Hello Ling, please forgive me if I call your name wrong. I am glad that you
find my repo useful and yeah, my repo will get into problems bcuz it was my
very first time to create a docker-compose yml file to combine every image
of big data tools. However, it is a very good chance for you to learn it
better through errors, and believe me, you will learn more than you think
if you can fix problems, bugs, etc,... I'm happy to see you fixed the
problem yourself.
Don't hesitate to connect to me and  good luck to your journey!
